[package]
name = "rustleet"
version = "0.1.0"
authors = ["vincentserpoul <vincent@serpoul>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
